parameters:
- name: AzureRegistryName
  displayName: Azure Registry Name
  type: string
- name: SubscriptionName
  displayName: Subscription Name
  type: string
- name: ImagestoKeep
  displayName: Images to keep
  type: string

jobs: 
  - job: 'clean_container_registry'
    pool: 
      vmImage: 'windows-latest'
    steps:
    - checkout: self